# Supabase configuration
# Refer to the Supabase CLI documentation for the full list of options:
# https://supabase.com/docs/guides/cli

project_id = "madena"

[auth]
enable_signup = false
[auth.email]
enable_signup = false
enable_confirmations = false

[storage]
[storage.buckets.media]
public = true
