-- ============================================================
-- الصيدليات الحقيقية في طيبة الإمام (28 صيدلية) — من ملف الصيدليات.xlsx
-- التصنيف: pharmacies | تُدرج فقط إن لم تكن موجودة (idempotent)
-- ============================================================

insert into public.places (name, slug, description, category_id, address, is_published) select 'محمد الخضر', 'mohammad-al-khadar', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: محمد الخضر', (select id from public.categories where slug='pharmacies'), 'طريق صوران _ مقابل عيادة د. محمود العبد الله', true where not exists (select 1 from public.places where slug = 'mohammad-al-khadar');
insert into public.places (name, slug, description, category_id, address, is_published) select 'ناريمان', 'nariman', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: ناريمان المنصور', (select id from public.categories where slug='pharmacies'), 'طريق المؤسسة - شمال دوار المدرسة الريفية', true where not exists (select 1 from public.places where slug = 'nariman');
insert into public.places (name, slug, description, category_id, address, is_published) select 'حسام العبد الله', 'hossam-al-abdallah', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: حسام العبد الله', (select id from public.categories where slug='pharmacies'), 'الشارع الرئيسي - شرق دوار البلدية بـ 300م', true where not exists (select 1 from public.places where slug = 'hossam-al-abdallah');
insert into public.places (name, slug, description, category_id, address, is_published) select 'المهند', 'al-muhannad', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: عزيزة العجمي', (select id from public.categories where slug='pharmacies'), 'الشارع الرئيسي - مقابل ساحة الحرية', true where not exists (select 1 from public.places where slug = 'al-muhannad');
insert into public.places (name, slug, description, category_id, address, is_published) select 'ندى', 'nada', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: ندى الرحال', (select id from public.categories where slug='pharmacies'), 'الشارع الرئيسي - مقابل عيادة د.عبد القادر الحسين', true where not exists (select 1 from public.places where slug = 'nada');
insert into public.places (name, slug, description, category_id, address, is_published) select 'الماسة', 'almasa', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: بيان الخطيب', (select id from public.categories where slug='pharmacies'), 'الشارع الرئيسي - شرق دوار البلدية', true where not exists (select 1 from public.places where slug = 'almasa');
insert into public.places (name, slug, description, category_id, address, is_published) select 'محمد العيسى', 'mohammad-al-issa', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: محمد العيسى', (select id from public.categories where slug='pharmacies'), 'الشارع الرئيسي - مقابل ساحة السرافيس القديمة', true where not exists (select 1 from public.places where slug = 'mohammad-al-issa');
insert into public.places (name, slug, description, category_id, address, is_published) select 'الشفاء', 'al-shifa', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: محمود الخطاب', (select id from public.categories where slug='pharmacies'), 'الشارع الرئيسي - مقابل عيادة د. هشام الخطاب', true where not exists (select 1 from public.places where slug = 'al-shifa');
insert into public.places (name, slug, description, category_id, address, is_published) select 'بيت العافية', 'bayt-al-afiya', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: هاني خطاب', (select id from public.categories where slug='pharmacies'), 'الشارع الرئيسي - شرق عيادة د. هشام الخطاب', true where not exists (select 1 from public.places where slug = 'bayt-al-afiya');
insert into public.places (name, slug, description, category_id, address, is_published) select 'شام', 'sham', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: بثينة العثمان', (select id from public.categories where slug='pharmacies'), 'الشارع الرئيسي جانب مكتب الفؤاد', true where not exists (select 1 from public.places where slug = 'sham');
insert into public.places (name, slug, description, category_id, address, is_published) select 'حارثة', 'haritha', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: حارثة الحاج عمر', (select id from public.categories where slug='pharmacies'), 'الشارع الرئيسي - مقابل بقالية حيدر', true where not exists (select 1 from public.places where slug = 'haritha');
insert into public.places (name, slug, description, category_id, address, is_published) select 'القدس', 'al-quds', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: أحمد العيسى', (select id from public.categories where slug='pharmacies'), 'الشارع الرئيسي - شرق مشفى الجواش', true where not exists (select 1 from public.places where slug = 'al-quds');
insert into public.places (name, slug, description, category_id, address, is_published) select 'الكيال', 'al-kyal', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: ياسمين الكيال', (select id from public.categories where slug='pharmacies'), 'الشارع الرئيسي - مقابل الكازية القديمة', true where not exists (select 1 from public.places where slug = 'al-kyal');
insert into public.places (name, slug, description, category_id, address, is_published) select 'اليوسف', 'al-yousef', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: رابعة اليوسف', (select id from public.categories where slug='pharmacies'), 'الشارع الرئيسي - غرب عيادة د. هشام الخطاب بـ 150م', true where not exists (select 1 from public.places where slug = 'al-yousef');
insert into public.places (name, slug, description, category_id, address, is_published) select 'حسان', 'hassan', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: حسان الشيخ', (select id from public.categories where slug='pharmacies'), 'جنوب النادي الرياضي بـ 100م', true where not exists (select 1 from public.places where slug = 'hassan');
insert into public.places (name, slug, description, category_id, address, is_published) select 'خيرية', 'khairiya', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: خيرية عبد الرحمن', (select id from public.categories where slug='pharmacies'), 'جنوب دوار البلدية - أول طريق قمحانة', true where not exists (select 1 from public.places where slug = 'khairiya');
insert into public.places (name, slug, description, category_id, address, is_published) select 'الجمال', 'al-jamal', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: إيمان الحسين', (select id from public.categories where slug='pharmacies'), 'طريق صوران جانب ملبوسات حازم', true where not exists (select 1 from public.places where slug = 'al-jamal');
insert into public.places (name, slug, description, category_id, address, is_published) select 'ميّار', 'mayar', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: صبا السهوان', (select id from public.categories where slug='pharmacies'), 'طريق قمحانة - مقابل عيادة د. هشام الكيال', true where not exists (select 1 from public.places where slug = 'mayar');
insert into public.places (name, slug, description, category_id, address, is_published) select 'أنس', 'anas', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: أنس الأسود', (select id from public.categories where slug='pharmacies'), 'الشارع الرئيسي - جنوب المستوصف بـ 100م', true where not exists (select 1 from public.places where slug = 'anas');
insert into public.places (name, slug, description, category_id, address, is_published) select 'توفيق', 'tawfiq', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: توفيق الخطيب', (select id from public.categories where slug='pharmacies'), 'طريق النادي - شمال د.نجيب بـ 100م', true where not exists (select 1 from public.places where slug = 'tawfiq');
insert into public.places (name, slug, description, category_id, address, is_published) select 'سماهر', 'samaher', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: سماهر الخطاب', (select id from public.categories where slug='pharmacies'), 'جنوب مسجد الهدى بـ 50م', true where not exists (select 1 from public.places where slug = 'samaher');
insert into public.places (name, slug, description, category_id, address, is_published) select 'فخر', 'fakhr', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: فخر السيد محمد', (select id from public.categories where slug='pharmacies'), 'جنوب دوار صوران بـ 100م', true where not exists (select 1 from public.places where slug = 'fakhr');
insert into public.places (name, slug, description, category_id, address, is_published) select 'الخطيب', 'al-khatib', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: محمد الخطيب', (select id from public.categories where slug='pharmacies'), 'طريق صوران - غرب عيادة د. محمود العبدالله', true where not exists (select 1 from public.places where slug = 'al-khatib');
insert into public.places (name, slug, description, category_id, address, is_published) select 'المها', 'al-maha', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: مها العبدالله', (select id from public.categories where slug='pharmacies'), 'طريق قمحانة - جنوب مسجد الصالحية بـ 100 متر', true where not exists (select 1 from public.places where slug = 'al-maha');
insert into public.places (name, slug, description, category_id, address, is_published) select 'آلاء', 'alaa', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: آلاء الجواش', (select id from public.categories where slug='pharmacies'), 'طريق المؤسسة - شمال دوار المدرسة الريفية', true where not exists (select 1 from public.places where slug = 'alaa');
insert into public.places (name, slug, description, category_id, address, is_published) select 'بيت الشفاء', 'bayt-al-shifa', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: نسرين قناص', (select id from public.categories where slug='pharmacies'), 'طريق صوران - نهاية طريق النادي', true where not exists (select 1 from public.places where slug = 'bayt-al-shifa');
insert into public.places (name, slug, description, category_id, address, is_published) select 'سمر', 'samar', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: سمر الحسين', (select id from public.categories where slug='pharmacies'), 'الحي الشرقي - جنوب دوار صوران بـ 300م', true where not exists (select 1 from public.places where slug = 'samar');
insert into public.places (name, slug, description, category_id, address, is_published) select 'حنان', 'hanan', 'صيدلية في مدينة طيبة الإمام — الصيدلاني/ـة المسؤول: حنان عبد الرحمن', (select id from public.categories where slug='pharmacies'), 'طريق المؤسسة - جنوب المدرسة الريفية', true where not exists (select 1 from public.places where slug = 'hanan');
